In [3]:
# Import necessary modules
import sys
sys.path.append('../src')  # Add the src directory to the system path
from dataset import load_data, save_data

# Load the raw dataset
raw_data_path = '../data/raw/ie2019.csv'
data = load_data(raw_data_path)
print("Raw Data:")
data.head()

Raw Data:

,SOURCE,OWNERSHIP_IND,CLUSTER_DEFN,UEN,REF_YR,EA_IND,TOPLINE_IND,TOT_EMP,FLAD_OR,FLAD_PROFIT,...,NSME_IND,IE_IND,PCAT,OR_CAT,Age_Band,IE_IND_BEF,PCAT_BEF,SOURCE_BEF,IMPUTE,FINAL_IE
0,NaN,1.LOCAL,11 Wholesale,00016800M,2019,1,1,1.0,362141.0,80178.0,...,0,0,0,<=1mil,> 30 Years,NaN,NaN,NaN,0,A
1,NaN,1.LOCAL,21 Other Services Industries,00020100J,2019,1,1,2.0,144595.0,6837.0,...,0,0,0,<=1mil,> 30 Years,NaN,NaN,NaN,0,A
2,GMAP,1.LOCAL,21 Other Services Industries,00022500B,2019,1,1,0.0,21635.0,21635.0,...,0,1,2,<=1mil,> 30 Years,1.0,2.0,NaN,0,B
3,GMAP,1.LOCAL,11 Wholesale,00027700B,2019,1,1,2.0,507221.0,-5679.0,...,0,1,1,<=1mil,> 30 Years,1.0,1.0,NaN,0,B
4,NaN,1.LOCAL,11 Wholesale,00045500L,2019,1,1,0.0,448339.0,34272.0,...,0,0,0,<=1mil,> 30 Years,NaN,NaN,NaN,0,A